version: "3"
services:
  witness:
    image: local/revpop-core
    volumes:
      - ./my-genesis.json:/revpop/genesis.json:ro
    command: witness_node
      --rpc-endpoint 0.0.0.0:8090
      --p2p-endpoint 0.0.0.0:2771
      --enable-stale-production
      --seed-nodes []
      --genesis-json /revpop/genesis.json
      --private-key [\""RVP6JaiMEZZ57Q75Xh3kVbJ4owX13p7f1kkV76B3xLNFuWHVbRSyZ"\",\""5KXbCDyCPL3eGX6xX5uJHVwoAYheF7L5fKf67oQocgJA8kNvVHF"\"]
      --witness \""1.6.1"\"
      --witness \""1.6.2"\"
      --witness \""1.6.3"\"
      --witness \""1.6.4"\"
      --witness \""1.6.5"\"
      --witness \""1.6.6"\"
      --witness \""1.6.7"\"
      --witness \""1.6.8"\"
      --witness \""1.6.9"\"
      --witness \""1.6.10"\"
      --witness \""1.6.11"\"
      --witness \""1.6.12"\"
      --witness \""1.6.13"\"
      --witness \""1.6.14"\"
      --witness \""1.6.15"\"
      --witness \""1.6.16"\"
      --witness \""1.6.17"\"
      --witness \""1.6.18"\"
      --witness \""1.6.19"\"
      --witness \""1.6.20"\"
      --witness \""1.6.21"\"
      --witness \""1.6.22"\"
      --witness \""1.6.23"\"
      --witness \""1.6.24"\"
      --witness \""1.6.25"\"
      --witness \""1.6.26"\"
      --witness \""1.6.27"\"
      --witness \""1.6.28"\"
      --witness \""1.6.29"\"
      --witness \""1.6.30"\"
      --witness \""1.6.31"\"
      --witness \""1.6.32"\"
      --witness \""1.6.33"\"
      --witness \""1.6.34"\"
      --witness \""1.6.35"\"
      --witness \""1.6.36"\"
      --witness \""1.6.37"\"
      --witness \""1.6.38"\"
      --witness \""1.6.39"\"
      --witness \""1.6.40"\"
      --witness \""1.6.41"\"
      --witness \""1.6.42"\"
      --witness \""1.6.43"\"
      --witness \""1.6.44"\"
      --witness \""1.6.45"\"
      --witness \""1.6.46"\"
      --witness \""1.6.47"\"
      --witness \""1.6.48"\"
      --witness \""1.6.49"\"
      --witness \""1.6.50"\"
      --witness \""1.6.51"\"
      --witness \""1.6.52"\"
      --witness \""1.6.53"\"
      --witness \""1.6.54"\"
      --witness \""1.6.55"\"
      --witness \""1.6.56"\"
      --witness \""1.6.57"\"
      --witness \""1.6.58"\"
      --witness \""1.6.59"\"
      --witness \""1.6.60"\"
      --witness \""1.6.61"\"
      --witness \""1.6.62"\"
      --witness \""1.6.63"\"

  proxy:
    image: local/revpop-core
    volumes:
      - ./my-genesis.json:/revpop/genesis.json:ro
    depends_on:
      - witness
    ports:
      - "8090:8090"
    command: witness_node
      --rpc-endpoint 0.0.0.0:8090
      --p2p-endpoint 0.0.0.0:2771
      --seed-nodes [\"witness:2771\"]
      --genesis-json /revpop/genesis.json
      --plugins "witness account_history market_history grouped_orders api_helper_indexes"

  init:
    image: local/revpop-core
    volumes:
      - ./init.txt:/revpop/init.txt
    depends_on:
      - proxy
    command: cat /revpop/init.txt | tee -a cli_wallet
      --server-rpc-endpoint ws://proxy:8090
      --chain-id 5a93b204cb70787cb077025d74480c59f69e47b9decad9e4ddba868bc913dc65

